# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tabla_horas.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Ui_Tabla_h(object):
    def setupUi(self, Ui_Tabla_h):
        Ui_Tabla_h.setObjectName("Ui_Tabla_h")
        Ui_Tabla_h.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Ui_Tabla_h.sizePolicy().hasHeightForWidth())
        Ui_Tabla_h.setSizePolicy(sizePolicy)
        Ui_Tabla_h.setMinimumSize(QtCore.QSize(1150, 900))
        Ui_Tabla_h.setBaseSize(QtCore.QSize(1200, 900))
        self.centralwidget = QtWidgets.QWidget(Ui_Tabla_h)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_2.addWidget(self.textEdit, 0, 1, 1, 1)

        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(24)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        self.tableWidget.setFont(font)
        
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter)
        item.setTextAlignment(QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVCenter)
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVCenter)
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(200)
        self.gridLayout_2.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 1, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: green;")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        #Ui_Tabla_h.setCentralWidget(self.centralwidget)
        #self.menubar = QtWidgets.QMenuBar(Ui_Tabla_h)
        #self.menubar.setGeometry(QtCore.QRect(0, 0, 1150, 21))
        #self.menubar.setObjectName("menubar")
        #self.menumenu = QtWidgets.QMenu(self.menubar)
        #self.menumenu.setObjectName("menumenu")
        #Ui_Tabla_h.setMenuBar(self.menubar)
        #self.statusbar = QtWidgets.QStatusBar(Ui_Tabla_h)
        #self.statusbar.setObjectName("statusbar")
        #Ui_Tabla_h.setStatusBar(self.statusbar)
        #self.menubar.addAction(self.menumenu.menuAction())

        self.retranslateUi(Ui_Tabla_h)
        QtCore.QMetaObject.connectSlotsByName(Ui_Tabla_h)

    def retranslateUi(self, Ui_Tabla_h):
        _translate = QtCore.QCoreApplication.translate
        Ui_Tabla_h.setWindowTitle(_translate("Ui_Tabla_h", "Hora por Hora"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Ui_Tabla_h", "07-08"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Ui_Tabla_h", "08-09"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Ui_Tabla_h", "09-10"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Ui_Tabla_h", "10-11"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Ui_Tabla_h", "11-12"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Ui_Tabla_h", "12-13"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Ui_Tabla_h", "13-14"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("Ui_Tabla_h", "14-15"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("Ui_Tabla_h", "15-16"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("Ui_Tabla_h", "16-17"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("Ui_Tabla_h", "17-18"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("Ui_Tabla_h", "18-19"))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("Ui_Tabla_h", "19-20"))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("Ui_Tabla_h", "20-21"))
        item = self.tableWidget.verticalHeaderItem(14)
        item.setText(_translate("Ui_Tabla_h", "21-22"))
        item = self.tableWidget.verticalHeaderItem(15)
        item.setText(_translate("Ui_Tabla_h", "22-23"))
        item = self.tableWidget.verticalHeaderItem(16)
        item.setText(_translate("Ui_Tabla_h", "23-00"))
        item = self.tableWidget.verticalHeaderItem(17)
        item.setText(_translate("Ui_Tabla_h", "00-01"))
        item = self.tableWidget.verticalHeaderItem(18)
        item.setText(_translate("Ui_Tabla_h", "01-02"))
        item = self.tableWidget.verticalHeaderItem(19)
        item.setText(_translate("Ui_Tabla_h", "02-03"))
        item = self.tableWidget.verticalHeaderItem(20)
        item.setText(_translate("Ui_Tabla_h", "03-04"))
        item = self.tableWidget.verticalHeaderItem(21)
        item.setText(_translate("Ui_Tabla_h", "04-05"))
        item = self.tableWidget.verticalHeaderItem(22)
        item.setText(_translate("Ui_Tabla_h", "05-06"))
        item = self.tableWidget.verticalHeaderItem(23)
        item.setText(_translate("Ui_Tabla_h", "06-07"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Ui_Tabla_h", "Cantidad de Arneses"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Ui_Tabla_h", "Mejor Tiempo"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Ui_Tabla_h", "Promedio Tiempo ciclo"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Ui_Tabla_h", "Tiempo sin usar la máquina"))
        self.label_4.setText(_translate("Ui_Tabla_h", "                                                                            NOTAS"))
        self.label_3.setText(_translate("Ui_Tabla_h", "TextLabel"))
        self.label.setText(_translate("Ui_Tabla_h", "HORA POR HORA-TORQUE3"))
        self.label_2.setText(_translate("Ui_Tabla_h", "TextLabel"))
        #self.menumenu.setTitle(_translate("Ui_Tabla_h", "menu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ui_Tabla_h = QtWidgets.QMainWindow()
    ui = Ui_Ui_Tabla_h()
    ui.setupUi(Ui_Tabla_h)
    Ui_Tabla_h.show()
    sys.exit(app.exec_())

