# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tabla_errores.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TableErrors(object):
    def setupUi(self, TableErrors):
        TableErrors.setObjectName("TableErrors")
        TableErrors.resize(1323, 835)
        self.centralwidget = QtWidgets.QWidget(TableErrors)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 10, 1159, 1025))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(97)
        sizePolicy.setVerticalStretch(69)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setBaseSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(50)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(135)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(100)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        #TableErrors.setCentralWidget(self.centralwidget)
        #self.menubar = QtWidgets.QMenuBar(TableErrors)
        #self.menubar.setGeometry(QtCore.QRect(0, 0, 1323, 21))
        #self.menubar.setObjectName("menubar")
        #TableErrors.setMenuBar(self.menubar)
        #self.statusbar = QtWidgets.QStatusBar(TableErrors)
        #self.statusbar.setObjectName("statusbar")
        #TableErrors.setStatusBar(self.statusbar)

        self.retranslateUi(TableErrors)
        QtCore.QMetaObject.connectSlotsByName(TableErrors)

    def retranslateUi(self, TableErrors):
        _translate = QtCore.QCoreApplication.translate
        TableErrors.setWindowTitle(_translate("TableErrors", "MainWindow"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("TableErrors", "Cavidad"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("TableErrors", "Fase"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("TableErrors", "Angulo-Final"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("TableErrors", "Torque-Final"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("TableErrors", "Angulo-Minimo"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("TableErrors", "Angulo-Maximo"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("TableErrors", "Torque-Minimo"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("TableErrors", "Torque-Maximo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TableErrors = QtWidgets.QMainWindow()
    ui = Ui_TableErrors()
    ui.setupUi(TableErrors)
    TableErrors.show()
    sys.exit(app.exec_())

